---
# File: install.yml - package installation tasks for Nomad

- name: OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nomad_os_packages }}"
  tags: installation

- name: Check Nomad package checksum file
  local_action: stat path="{{ role_path }}/files/nomad_{{ nomad_version }}_SHA256SUMS"
  become: false
  run_once: true
  tags: installation
  register: nomad_checksum

- name: Get Nomad package checksum file
  local_action: get_url url="{{ nomad_checksum_file_url }}" dest="{{ role_path }}/files/nomad_{{ nomad_version }}_SHA256SUMS"
  become: false
  run_once: true
  tags: installation
  when: nomad_checksum.stat.exists == False

- name: Get Nomad package checksum
  local_action: shell grep "{{ nomad_pkg }}" "{{ role_path }}/files/nomad_{{ nomad_version }}_SHA256SUMS"  | awk '{print $1}'
  become: false
  register: nomad_sha256
  tags: installation

- name: Check Nomad package file
  local_action: stat path="{{ role_path }}/files/{{ nomad_pkg }}"
  become: false
  register: nomad_package

- name: Download Nomad
  local_action: get_url url="{{ nomad_zip_url }}" dest="{{ role_path }}/files/{{ nomad_pkg }}" checksum="sha256:{{ nomad_sha256.stdout }}" timeout="42"
  become: false
  tags: installation
  when: nomad_package.stat.exists == False

- name: Create Temporary Directory for Extraction
  local_action:
    module: tempfile
    state: directory
    prefix: ansible-nomad.
  become: false
  register: install_temp
  tags: installation

- name: Unarchive Nomad
  local_action: unarchive src="{{ role_path }}/files/{{ nomad_pkg }}" dest="{{ install_temp.path }}/" creates="{{ install_temp.path }}/nomad"
  become: false
  tags: installation

- name: Install Nomad
  copy:
    src: "{{ install_temp.path }}/nomad"
    dest: "{{ nomad_bin_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
  tags: installation

- name: Cleanup
  local_action: file path="{{ install_temp.path }}" state="absent"
  become: false
  tags: installation
