image: alpine:latest


stages:
  - test
  - build
  - review
  - build-release
  - deploy-release

test:
  stage: test
  image: python:3.6.0-alpine   
  script:
    - "apk add -U openssl curl tar gzip bash ca-certificates git"
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt -r requirements-test.txt"
    - "python -m unittest discover -s tests/"
    - "coverage run -m unittest discover -s tests/"
    - "coverage report --include crawler/crawler.py"

build-master:
  stage: build
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_app:master ."
    - "docker push registry.service.consul:5000/crawler_app:master"
  only:
    - master
  when: manual

recreate-mongodb-master:
  stage: build
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-master-job"
    - "curl --request POST --data @deploy/mongodb-master.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - master
  when: manual

build-branch:
  stage: build
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_app:branch ."
    - "docker push registry.service.consul:5000/crawler_app:branch"
  only:
    - branches
  except:
    - master

recreate-mongodb-branch:
  stage: build
  script:   
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-branch-job"
    - "curl --request POST --data @deploy/mongodb-branch.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - branches
  except:
    - master
  when: manual

run-review-master:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-app-master-job"
    - "curl --request POST --data @deploy/app-master.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - master
  when: manual


stop-app-master:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-app-master-job"
  only:
    - master  
  when: manual

stop-mongodb-master:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-master-job"
  only:
    - master
  when: manual

run-review-branch:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-app-branch-job"
    - "curl --request POST --data @deploy/app-branch.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - branches
  except:
    - master

stop-app-branch:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-app-branch-job"
  only:
    - branches
  except:
    - master
  when: manual

stop-mongodb-branch:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-branch-job"
  only:
    - branches
  except:
    - master
  when: manual

build-release:
  stage: build-release
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_app:release ."
    - "docker push registry.service.consul:5000/crawler_app:release"
  only:
    - master
  when: manual

deploy-release:
  stage: deploy-release
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-app-release-job"
    - "curl --request POST --data @deploy/app-release.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - master
  when: manual
