image: alpine:latest

stages:
  - test
  - build
  - review
  - build-release
  - deploy-release

test:
  stage: test
  image: python:3.6.0-alpine   
  script:
    - "apk add -U openssl curl tar gzip bash ca-certificates git"
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt -r requirements-test.txt"
    - "python -m unittest discover -s tests/"
    - "coverage run -m unittest discover -s tests/"
    - "coverage report --include ui/ui.py"

build-master:
  stage: build
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_ui:master ."
    - "docker push registry.service.consul:5000/crawler_ui:master"
  only:
    - master
  when: manual

recreate-mongodb-master:
  stage: build
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-master-job"
    - "curl --request POST --data @deploy/mongodb-master.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - master
  when: manual

build-branch:
  stage: build
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_ui:branch ."
    - "docker push registry.service.consul:5000/crawler_ui:branch"
  only:
    - branches
  except:
    - master

recreate-mongodb-branch:
  stage: build
  script:   
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-branch-job"
    - "curl --request POST --data @deploy/mongodb-branch.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - branches
  except:
    - master
  when: manual

run-review-master:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-ui-master-job"
    - "curl --request POST --data @deploy/ui-master.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - master
  when: manual
  environment:
    name: master
    url: https://crawler-master/


stop-ui-master:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-ui-master-job"
  only:
    - master  
  when: manual

stop-mongodb-master:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-master-job"
  only:
    - master
  when: manual

run-review-branch:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-ui-branch-job"
    - "curl --request POST --data @deploy/ui-branch.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - branches
  except:
    - master
  environment:
    name: branch
    url: https://crawler-branch/


stop-ui-branch:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-ui-branch-job"
  only:
    - branches
  except:
    - master
  when: manual

stop-mongodb-branch:
  stage: review
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/mongodb-branch-job"
  only:
    - branches
  except:
    - master
  when: manual

build-release:
  stage: build-release
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_ui:release ."
    - "docker push registry.service.consul:5000/crawler_ui:release"
  only:
    - master
  when: manual

deploy-release:
  stage: deploy-release
  script:
    - "apk add -U curl git"
    - "curl --request DELETE http://nomad-servers.service.consul:4646/v1/job/crawler-ui-release-job"
    - "curl --request POST --data @deploy/ui-release.json http://nomad-servers.service.consul:4646/v1/jobs"
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://crawler/

