image: alpine:latest


stages:
  - test
  - build

test:
  stage: test
  image: python:3.6.0-alpine   
  script:
    - "apk add -U openssl curl tar gzip bash ca-certificates git"
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt -r requirements-test.txt"
    - "python -m unittest discover -s tests/"
    - "coverage run -m unittest discover -s tests/"
    - "coverage report --include ui/ui.py"

build:
  stage: build
  image: docker:git
  script:
    - "docker build -t registry.service.consul:5000/crawler_ui:master ."
    - "docker push registry.service.consul:5000/crawler_ui:master"
