---
- name: Self signet cert install
  hosts: tag_nomad-instances
  become: true
  become_user: root
  vars:
    self_signed_certs:
      - key: "traefik.key"
        cert: "traefik.crt"
        dir: "/srv/certs"
      - key: "registry.key"
        cert: "registry.crt"
        dir: "/srv/certs"
    self_signet_CA:
      - cert: "CA.crt"
        dir: "/usr/local/share/ca-certificates/"
      - cert: "CA.crt"
        dir: "/etc/docker/certs.d/"
  tasks:
    - name: Create dirs for certs and key
      file:
        path: "{{ item.dir }}"
        state: directory
        mode: 700
      with_items: "{{ self_signed_certs }}"

    - name: Create dirs for CA certs 
      file:   
        path: "{{ item.dir }}"
        state: directory
        mode: 700  
      with_items: "{{ self_signet_CA }}"

    - name: Copy created certs
      copy:
        src: "../files/certs/{{ item.cert }}"        
        dest: "{{ item.dir }}"
      with_items: "{{ self_signed_certs }}"

    - name: Copy created keys
      copy:
        src: "../files/certs/{{ item.key }}"
        dest: "{{ item.dir }}"
      with_items: "{{ self_signed_certs }}"

    - name: Copy created CA cert
      copy:   
        src: "../files/certs/{{ item.cert }}"
        dest: "{{ item.dir }}"
      with_items: "{{ self_signet_CA }}"

    - name: Update CA Certs
      shell: update-ca-certificates
