---
- name: Installing consul on consul_instances
  hosts: tag_consul-instances
  become: true
  roles:
    - role: brianshumate.consul 
      consul_group_name: "tag_consul-instances"      
      consul_enable_script_checks: true
      consul_enable_local_script_checks: true
      consul_recursors: ['8.8.8.8', '8.8.4.4']
      consul_client_address: "0.0.0.0" 
      consul_dnsmasq_enable: yes
