---
# Install node in GCP for Nomad cluster
- name: DIGITA Instance
  hosts: localhost
  vars:
    service_account_email: "87352832204-compute@developer.gserviceaccount.com"
    credentials_file: "~/gcp/infra.json"
    project_id: "docker-9"
    cluster_zone: "europe-west1-b"
    provisioner_user: "ansible"
    provisioner_key: "~/.ssh/ansible.pub"
    image_family: "ubuntu-1604-lts"    
    cluster_node:
      - name: "cluster-node-01"
        disk_size: 30
        machine_type: "n1-standard-1"
        consul_node_role: "bootstrap"
        nomad_node_role: "both"
        snode: true
        gitlab: true
        prometheus: false
        registry: true
        efk: false
        mongodb: true
      - name: "cluster-node-02"
        disk_size: 30
        machine_type: "n1-standard-1"
        consul_node_role: "server"
        nomad_node_role: "both"
        snode: true
        gitlab: false
        prometheus: true
        registry: false
        efk: false
        mongodb: true
      - name: "cluster-node-03"
        disk_size: 30
        machine_type: "n1-standard-1"
        consul_node_role: "server"
        nomad_node_role: "both"
        snode: true
        gitlab: false
        prometheus: false
        registry: false
        efk: true
        mongodb: true
  tasks:
    - name: Create Firewall Rule for http/s access
      gce_net:
        name: default
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        fwname: "cluster-firewall-rule"
        allowed: tcp:80;tcp:443;tcp:1022
        state: "present"
        target_tags: "cluster-node"
        src_range: ['0.0.0.0/0']

    - name: create a disk for node
      gce_pd:
         name: "disk-{{ item.name }}"
         disk_type: pd-standard
         size_gb: "{{ item.disk_size }}"
         image_family: "{{ image_family }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         zone: "{{ cluster_zone }}"
         state: present
      register: disk
      with_items: "{{ cluster_node }}"

    - name: Get the default SSH key
      command: cat "{{ provisioner_key }}"
      register: ssh_key

    - name: create nomad cluster node instances
      gce:
        instance_names: "{{ item.name }}"
        zone: "{{ cluster_zone }}"
        machine_type: "{{ item.machine_type }}"
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disks:
           - name: "disk-{{ item.name }}"
             mode: READ_WRITE
        metadata : '{ 
             "startup-script" : "apt-get update",
             "sshKeys": "{{ provisioner_user }}:{{ ssh_key.stdout }}",
             "snode": "{{ item.snode }}",
             "gitlab": "{{ item.gitlab }}",
             "prometheus": "{{ item.prometheus }}",
             "registry": "{{ item.registry }}",
             "efk": "{{ item.efk }}",
             "mongodb": "{{ item.mongodb }}",
             "consul_node_role" : "{{ item.consul_node_role }}",
             "nomad_node_role" : "{{ item.nomad_node_role }}"
          }'
        tags:
          - cluster-node
          - consul-instances
          - nomad-instances
      register: gce
      with_items: "{{ cluster_node }}"
