---
- name: Copy and run jobs nomad cluster
  hosts: tag_nomad-instances
  become: true
  vars:
    nomad_jobs_dir: "/srv/nomad/jobs"
    nomad_jobs_file:
#       - "fabio.nomad"
#       - "nginx.nomad"
#       - "traefik.nomad"
#       - "hashi-ui.nomad"
#       - "gitlab.nomad"
#       - "mongodb.nomad"
#       - "registry.nomad"
#       - "gitlab-consul.nomad"
#       - "gitlab-runner.nomad"
#       - "rabbitmq.nomad"
#       - "crawler-master.nomad" 
        - "test.nomad"
  tasks:
    - name: Copy jobs config files into node
      copy:
        src: "../files/nomad/{{ item }}"
        dest: "{{ nomad_jobs_dir }}"
      with_items: "{{ nomad_jobs_file }}"

    - name: Run jobs into nomad cluster
      run_once: true
      shell: "nomad run {{ item }}" 
      args:
        chdir: "{{ nomad_jobs_dir }}"
      with_items: "{{ nomad_jobs_file }}" 
