---
- name: Installing nomad on nomad-instances
  hosts: tag_nomad-instances
  become: true
  roles:
    - role: brianshumate.nomad
      nomad_group_name: "tag_nomad-instances"      
      nomad_docker_enable: "true"
      nomad_use_consul: "true"
      nomad_rejoin_after_leave: "true"
      nomad_bootstrap_expect: 3
      nomad_options: { 'driver.raw_exec.enable': '1' }
      nomad_bind_address: "0.0.0.0"
