---
- name: Copy config files for traefik
  hosts: tag_nomad-instances
  become: true
  vars:
    conf_file:
      - src: "../files/traefik/traefik.toml"
        dest: "traefik.toml"
        dir: "/srv/traefik"
  tasks:
    - name: Create dirs
      file:
        path: "{{ item.dir }}"
        state: directory
      with_items: "{{ conf_file }}"
    - name: Copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dir }}/{{ item.dest }}"
      with_items: "{{ conf_file }}"

