{
 "title": "crawler",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pages parsed per 1 min",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_pages_parsed{job=\"crawler-app\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Site connection time sum per 1 min",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_site_connection_time_sum{job=\"crawler-app\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page parse time sum per 1 min",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_page_parse_time_sum{job=\"crawler-app\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}