{
 "title": "crawler",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "site_connection_time_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum{job=\"crawler-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "page_parse_time_sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_page_parse_time_sum{job=\"crawler-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pages_parsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_pages_parsed{job=\"crawler-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}